set(CTEST_PROJECT_NAME "crash")
set(CTEST_NIGHTLY_START_TIME "21:00:00 EDT")

set(CTEST_DROP_METHOD "rmt")
set(CTEST_DROP_SITE "192.168.0.255")
set(CTEST_DROP_LOCATION "")
set(CTEST_DROP_SITE_CDASH TRUE)
